services:
    last.service:
        class: AppBundle\Service\LastService
        arguments: [@guzzle, %last_key%, %last_url%, %spotify_url%, %spotify_playlist_create_url%, %spotify_playlist_add_url%]




